name: Deploy static site to S3

on:
#   push:
#     branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}

jobs:
  deploy:
    name: Sync to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync site to S3 bucket
        run: |
          aws s3 sync . s3://$S3_BUCKET_NAME \
            --delete \
            --no-progress \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "DevOps/*" \
            --exclude "DevOps/**" \
            --exclude "**/*.ts" \
            --exclude "**/.terraform/*" \
            --exclude "**/*.tf" \
            --exclude "**/*.tfvars" \
            --exclude "README.md" \
            --exclude "LICENSE" \
            --exclude ".gitignore"

      - name: Show website endpoint hint
        run: |
          echo "Synced to s3://$S3_BUCKET_NAME"
          echo "If static website hosting is enabled, endpoint is likely: http://$S3_BUCKET_NAME.s3-website-${AWS_REGION}.amazonaws.com"


